FROM alpine

LABEL lduhamel="lduhamel@student.s19.be"

#COPY FILES
COPY srcs/start.sh /tmp/start.sh
COPY srcs/telegraf.conf /etc/telegraf/telegraf.conf

#PACKAGES
RUN apk update \
    && apk upgrade
RUN apk add openrc --no-cache
RUN apk add influxdb
RUN apk add telegraf --repository http://dl-3.alpinelinux.org/alpine/edge/community/ --allow-untrusted --no-cache

#START
RUN chmod 777 /tmp/start.sh
CMD sh ./tmp/start.sh