FROM alpine

#COPY
COPY srcs/start.sh /tmp/start.sh
COPY srcs/telegraf.conf /etc/telegraf/telegraf.conf

#PACKAGES
RUN apk update
RUN apk upgrade
RUN apk add openrc --no-cache
RUN apk add influxdb
RUN apk add telegraf --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted --no-cache

#START
RUN chmod 777 /tmp/start.sh
CMD sh ./tmp/start.sh