FROM alpine

#COPY
COPY srcs/start.sh /tmp/start.sh
#COPY srcs/telegraf.conf /etc/telegraf/telegraf.conf

#PACKAGES
RUN apk update
RUN apk upgrade
RUN apk add openrc --no-cache
RUN apk add influxdb
#RUN apk add telegraf 
#ß--repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted --no-cache
#RUN apk add wget
RUN wget https://dl.influxdata.com/telegraf/releases/telegraf-1.16.3_linux_amd64.tar.gz
RUN tar xf telegraf-1.16.3_linux_amd64.tar.gz \
   && rm telegraf-1.16.3_linux_amd64.tar.gz
RUN mv telegraf-1.16.3 telegraf
COPY srcs/telegraf.conf /telegraf/etc/telegraf/telegraf.conf

#START
RUN chmod 777 /tmp/start.sh
CMD sh ./tmp/start.sh