apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql-img
        ports:
        - containerPort: 3306
        imagePullPolicy: Never
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 4
          periodSeconds: 4
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-claim
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-serv
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
  type: ClusterIP



# #        env:
# #        - name: MYSQL_ROOT_PASSWORD
# #          value:
# #        - name: MYSQL_USER
# #          valueFrom:
# #            secretKeyRef:
# #              name: mysql-secret
# #              key: mysql-username
# #        - name: MYSQL_PASSWORD
# #          valueFrom:
# #            secretKeyRef:
# #              name: mysql-secret
# #              key: mysql-password


# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql-service
#   labels:
#       app: mysql
# spec:
#   ports:
#   - port: 3306
#     protocol: TCP
#   selector:
#     app: mysql
#     tier: mysql
#   loadBalancerIP: 192.168.99.115
# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mysql
#   # labels so that we can bind a Service to this Pod
#   labels:
#     app: mysql
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mysql
#       tier: mysql
#   template:
#     metadata:
#       labels:
#         app: mysql
#         tier: mysql
#     spec:
#       containers:
#       - name: mysql
#         image: mysql-img
#         imagePullPolicy: Never
#         livenessProbe:
#           tcpSocket:
#             port: 3306
#         ports:
#           - containerPort: 3306
#             name: mysql
#         volumeMounts:
#         - name: mysql
#           mountPath: /var/lib/mysql
#       volumes:
#       - name: mysql
#         persistentVolumeClaim:
#           claimName: mysql

