apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql-img
        ports:
        - containerPort: 3306
        imagePullPolicy: Never
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 4
          periodSeconds: 4
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-claim
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-serv
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
  type: ClusterIP
