apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-depl
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: php-img
        ports:
        - containerPort: 5000
        imagePullPolicy: Never
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 4
          periodSeconds: 4

---

apiVersion: v1
kind: Service
metadata:
  name: php-serv
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
  - port: 5000
  loadBalancerIP: 192.168.99.111