apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress-img
        ports:
        - containerPort: 5050
        imagePullPolicy: Never
        livenessProbe:
          tcpSocket:
            port: 5050
          initialDelaySeconds: 4
          periodSeconds: 4

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-serv
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
  - port: 5050
 # loadBalancerIP: 192.168.99.110
