FROM alpine

LABEL lduhamel="lduhamel@student.s19.be"

#COPY FILES
COPY srcs/start.sh /tmp/start.sh
COPY srcs/telegraf.conf /etc/telegraf/telegraf.conf

#PACKAGES
RUN apk update
RUN apk upgrade
RUN apk add openrc --no-cache
RUN apk add openssl pure-ftpd --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/ --allow-untrusted --no-cache
RUN apk add telegraf --repository http://dl-3.alpinelinux.org/alpine/edge/community/ --allow-untrusted --no-cache

#SSL
RUN mkdir -p /etc/ssl/private
RUN openssl req -x509 -nodes -days 7300 -subj "/C=BE/ST=Bruxelles/O=20/OU=lolo" -newkey rsa:2048 -keyout /etc/ssl/private/pure-ftpd.pem -out /etc/ssl/private/pure-ftpd.pem
RUN chmod 600 /etc/ssl/private/pure-ftpd.pem
RUN mkdir -p /run/openrc/ && touch /run/openrc/softlevel
RUN touch /run/openrc/softlevel

#USER
RUN adduser -D lolo
RUN echo "lolo:lolo" | chpasswd
RUN touch /home/lolo/test.txt

#START
RUN chmod 777 /tmp/start.sh
CMD sh ./tmp/start.sh
